include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Common and Useful
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_print: false
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_const: true
    unnecessary_final: false # Sometimes useful to allow for reassignments

    # Formatting and Style
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    use_super_parameters: true
    lines_longer_than_80_chars: false

    # Null Safety & Type Safety
    always_declare_return_types: true
    avoid_returning_null: true
    avoid_types_on_closure_parameters: false
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: true

    # Flutter-specific
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_positional_boolean_parameters: true
    flutter_style_todos: true

    # Performance
    no_logic_in_create_state: true
    avoid_redundant_argument_values: true

    # Readability
    annotate_overrides: true
    unnecessary_this: true
